<a href="https://colab.research.google.com/github/Codewithkaint/LearnGit/blob/main/PreTrainedModels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input,decode_predictions
import numpy as np

In [2]:
model=ResNet50(weights='imagenet')

102967424/102967424 [==============================] - 1s 0us/step


In [3]:
imgPath="/content/dog.10028.jpg"
img=image.load_img(imgPath,target_size=(224,224))
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
print(x)
print("***")
x=preprocess_input(x)
print(x)

[[[[102. 123.  92.]
   [ 97. 118.  87.]
   [113. 134. 103.]
   ...
   [ 63. 102.  55.]
   [ 15.  52.   9.]
   [ 44.  81.  38.]]

  [[ 55.  79.  47.]
   [ 78. 103.  71.]
   [ 79. 104.  72.]
   ...
   [ 47.  86.  39.]
   [ 38.  77.  33.]
   [ 45.  84.  40.]]

  [[ 63.  90.  57.]
   [ 69.  99.  65.]
   [ 64.  94.  60.]
   ...
   [ 34.  73.  26.]
   [ 30.  71.  27.]
   [ 22.  63.  19.]]

  ...

  [[ 50.  69.  49.]
   [ 33.  57.  35.]
   [ 46.  74.  51.]
   ...
   [ 63.  87.  65.]
   [ 44.  64.  37.]
   [ 40.  59.  31.]]

  [[ 37.  56.  36.]
   [ 27.  51.  29.]
   [ 18.  46.  23.]
   ...
   [  1.  25.   3.]
   [ 25.  45.  20.]
   [ 27.  45.  19.]]

  [[ 66.  85.  65.]
   [ 55.  79.  57.]
   [ 11.  39.  16.]
   ...
   [ 11.  35.  13.]
   [ 12.  32.   7.]
   [ 12.  30.   4.]]]]
***
[[[[ -11.939003     6.2210007  -21.68     ]
   [ -16.939003     1.2210007  -26.68     ]
   [  -0.939003    17.221      -10.68     ]
   ...
   [ -48.939003   -14.778999   -60.68     ]
   [ -94.939      -64.779     -

In [5]:
pred=model.predict(x)
print("Predicted = ",decode_predictions(pred,top=3)[0])

35363/35363 [==============================] - 0s 0us/step
Predicted =  [('n02109047', 'Great_Dane', 0.5685877), ('n02108089', 'boxer', 0.38449976), ('n04409515', 'tennis_ball', 0.010777834)]
